language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: inskips@gmail.com
  api_key:
    secure: JVu0enEuaB06sSegO1vFaTvYadZwf3Kvpm8iLDQDwK6cYRSvyFSlZ7UpukObEoFFISustI0r0nZ8xYqet9v+sB0wEQubKwo7UDmoZcni4dDH0NS/nZKPw/SwCA0GOWpXqWkQ8z1xdPpOCEmcoviQuDhLctG0wTsxYWimyc6Ost6kxkiDYNHT9NcBBIcFct2A722eLjOQFsZiVYkFy81Fi/ryhmZ36JIHiJL3ClIyAwbFCn9kR0YHrPeAhEOR0XopmBSaTDIwNuWRSXHLT8D71EhLodwfpZT+VOhahsPMDRl5qzXLdOt98djEG2GNyz9w2YrpQhk0HzL9Tr0UFZcTIzLnk4aTQStSyVNLe1HczecldIlqHvOnWw/m5Vdkue3dkCetOheCLAOHa2cytLsCB4ADvusY34JSF+ee4D5bFjBjIxzyuJ0ASsY0MYSNcHe6Bp8ejVflZv9gsviZusFuCvkKCzjOkLSm3z8RuApYtjgjUhhtVFDB0Jb2qfnJpdCGfrLIWk2GgEPniyNqcNLJ7+DwK37dOX+BJUK0iUSlKq/LpShGrSEtpf8D6o0FrT+qTJe3UktPIzdk434Pvly9lhARUD1GDSzig4MnGuDBuGsRScPyyN4EOW7I9ECnGda5NXRyfqotbEgN5telNoBS995JGtjyH2s9qnXkCmj7WXQ=
  on:
    tags: true
    repo: SkippyZA/ibt-telemetry
